service: aws-billing # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "ce:*"
       Resource:
         - "*"

functions:
  hello:
    handler: handler.set_lambda_return_format
    events:
      - http: GET /

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

custom:
  pythonRequirements:
    dockerizePip: false
  domain_endpoint: "awsbilling.api.gregsharpe.co.uk"
  customDomain:
    domainName: aws.api.gregsharpe.co.uk
    stage: dev
    basePath: ''
    certificateName: "api.gregsharpe.co.uk"
    createRoute53Record: true
