service: aws-running-instances # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  timeout: 20
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "ec2:*"
       Resource:
         - "*"

functions:
  hello:
    handler: handler.set_lambda_return_format
    events:
      - http: GET /

plugins:
  - serverless-domain-manager

custom:
  pythonRequirements:
    dockerizePip: false
  customDomain:
    domainName: ec2count.api.gregsharpe.co.uk
    stage: dev
    basePath: ''
    certificateName: "api.gregsharpe.co.uk"
    createRoute53Record: true
